# !/bin/bash

path=$(readlink -f ${BASH_SOURCE:-$0})
DIR_PATH=$(dirname $path)

echo "$DIR_PATH"

export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=$IGN_GAZEBO_SYSTEM_PLUGIN_PATH:$DIR_PATH/build
export IGN_GAZEBO_RESOURCE_PATH=$IGN_GAZEBO_RESOURCE_PATH:$DIR_PATH/models
